BlogApp.Mvc/Areas/Admin/Models/CategoryAddAjaxViewModel.cs
using BlogApp.Entities.Dtos;

namespace BlogApp.Mvc.Areas.Admin.Models
{
    public class CategoryAddAjaxViewModel
    {
        public CategoryAddDto CategoryAddDto { get; set; }
        public string CategoryAddPartial { get; set; }
        public CategoryDto CategoryDto { get; set; }
    }
}

BlogApp.Mvc/Areas/Admin/Models/CategoryUpdateAjaxViewModel.cs
using BlogApp.Entities.Dtos;

namespace BlogApp.Mvc.Areas.Admin.Models
{
    public class CategoryUpdateAjaxViewModel
    {
        public CategoryUpdateDto CategoryUpdateDto  { get; set; }
        public string CategoryUpdatePartial { get; set; }
        public CategoryDto CategoryDto { get; set; }
    }
}

BlogApp.Mvc/Areas/Admin/Models/ErrorViewModel.cs
namespace BlogApp.Mvc.Areas.Admin.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogApp.Mvc/Models/ErrorViewModel.cs
namespace BlogApp.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogApp.Mvc/Areas/Admin/Controllers/ArticleController.cs
using BlogApp.Services.Abstract;
using BlogApp.Shared.Utilities.Result.ComplexTypes;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;

        public ArticleController(IArticleService articleService)
        {
            _articleService = articleService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _articleService.GetAll();
            if (result.ResultStatus == ResultStatus.Success)
            {
                return View(result.Data);
            }
            return View();
        }
    }
}

BlogApp.Mvc/Areas/Admin/Controllers/CategoryController.cs
using BlogApp.Entities.Dtos;
using BlogApp.Mvc.Areas.Admin.Models;
using BlogApp.Services.Abstract;
using BlogApp.Shared.Utilities.Extensions;
using BlogApp.Shared.Utilities.Result.ComplexTypes;
using BlogApp.Shared.Utilities.Result.Concrete;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace BlogApp.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _categoryService.GetAllByNonDeleted();
            if (result.ResultStatus == ResultStatus.Success)
            {
                return View(result.Data);
            }
            return View();
        }

        public IActionResult Add()
        {
            return PartialView("_CategoryAddPartial");
        }
        [HttpPost]
        public async Task<IActionResult> Add(CategoryAddDto categoryAddDto)
        {
            if (ModelState.IsValid) //
            {
                var result = await _categoryService.Add(categoryAddDto, "Kerem");
                if (result.ResultStatus == ResultStatus.Success)
                {
                    var categoryAddAjaxModel = JsonSerializer.Serialize(new CategoryAddAjaxViewModel
                    {
                        CategoryDto = result.Data,
                        CategoryAddPartial = await this.RenderViewToStringAsync("_CategoryAddPartial", categoryAddDto)
                    });
                    return Json(categoryAddAjaxModel);

                }
            }
            var categoryAddAjaxErrorModel = JsonSerializer.Serialize(new CategoryAddAjaxViewModel
            {
                CategoryAddPartial = await this.RenderViewToStringAsync("_CategoryAddPartial", categoryAddDto)
            });
            return Json(categoryAddAjaxErrorModel);
        }
        public async Task<JsonResult> GetAllCategories()
        {
            var result = await _categoryService.GetAllByNonDeleted();
            var resultJson = JsonSerializer.Serialize(result.Data, new JsonSerializerOptions 
            {
                ReferenceHandler = ReferenceHandler.Preserve
            });
            return Json(resultJson);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int categoryId)
        {
            var result = await _categoryService.Delete(categoryId, "Kerem");
            var resultJson = JsonSerializer.Serialize(result);
            return Json(resultJson);
        }

        public async Task<IActionResult> Update(int categoryId)
        {
            var result = await _categoryService.GetCategoryUpdateDto(categoryId);
            if (result.ResultStatus == ResultStatus.Success)
            {
                return PartialView("_CategoryUpdatePartial", result.Data);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Update(CategoryUpdateDto categoryUpdateDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _categoryService.Update(categoryUpdateDto, "Kerem");
                if (result.ResultStatus==ResultStatus.Success){}
                {
                    var categoryUpdateAjaxModel = JsonSerializer.Serialize(new CategoryUpdateAjaxViewModel
                    {
                        CategoryDto = result.Data,
                        CategoryUpdatePartial = await this.RenderViewToStringAsync("_CategoryUpdatePartial", categoryUpdateDto)
                    });
                    return Json(categoryUpdateAjaxModel);
                }
            }
            else 
            {
                var categoryUpdateAjaxErrorModel = JsonSerializer.Serialize(new CategoryUpdateAjaxViewModel
                {
                    CategoryUpdatePartial = await this.RenderViewToStringAsync("_CategoryUpdatePartial", categoryUpdateDto)
                });
                return Json(categoryUpdateAjaxErrorModel);
            }
        }
    }
}

BlogApp.Mvc/Areas/Admin/Controllers/HomeController.cs
using BlogApp.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogApp.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BlogApp.Mvc/Controllers/HomeController.cs
using BlogApp.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogApp.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BlogApp.Mvc/Areas/Admin/Views/Article/Index.cshtml
@using BlogApp.Entities.Dtos;
@using BlogApp.Shared.Utilities.Result.ComplexTypes;

@model ArticleListDto
@{
    Layout = "_Layout";
    ViewBag.Title = "Makaleler Anasayfa";
}
@if (Model.ResultStatus == ResultStatus.Success)
{

    <h1 class="mt-4">Admin Makaleler</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">Makaleler</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Makaleler
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="articleTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Thumbnail</th>
                            <th>Date</th>
                            <th>Seo Author</th>
                            <th>Seo Description</th>
                            <th>Seo Tags</th>
                            <th>Oluşturan Kullanıcı</th>
                            <th>Oluşturulma Tarihi</th>
                            <th>Son Düzenleyen Kullanıcı</th>
                            <th>Son Düzenlenme Tarihi</th>
                            <th>Note</th>
                            <th>Görüntülenme Sayısı</th>
                            <th>Yorum Sayısı</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var article in Model.Articles)
                        {
                            <tr>
                                <td>@article.Id</td>
                                <td>@article.Title</td>
                                <td>@article.Thumbnail</td>
                                <td>@article.Date</td>
                                <td>@article.SeoAuthor</td>
                                <td>@article.SeoDescription</td>
                                <td>@article.SeoTags</td>
                                <td>@article.CreatedByName</td>
                                <td>@article.CreatedDate.ToShortDateString()</td>
                                <td>@article.ModifiedByName</td>
                                <td>@article.ModifiedDate.ToShortDateString()</td>
                                <td>@article.Note</td>
                                <td>@article.ViewsCount</td>
                                <td>@article.CommentCount</td>


                            </tr>
                        }


                    </tbody>
                </table>
            </div>
        </div>
    </div>

} 

@section Scripts
    {
    <script>
        $(document).ready(function () {
            $('#articleTable').DataTable({
                dom: "<'row'<'col-sm-3'l><'col-sm-6 text-center'B><'col-sm-3'f>>" +
                    "<'row'<'col-sm-12'tr>>" +
                    "<'row'<'col-sm-5'i><'col-sm-7'p>>",
                buttons: [
                    {
                        text: 'Ekle',
                        action: function (e, dt, node, config) {
                            alert('Ekle butonuna tıklandı');
                        },
                        className: 'btn btn-success'
                    },
                    {
                        text: 'Yenile',
                        action: function (e, dt, node, config) {
                            alert('Yenile butonuna tıklandı');
                        },
                        className: 'btn btn-warning'
                    }
                ],
                language: {
                    url: 'https://cdn.datatables.net/plug-ins/1.13.1/i18n/tr.json',
                }
            });
        });
    </script>
}

BlogApp.Mvc/Areas/Admin/Views/Category/Index.cshtml
@using BlogApp.Shared.Utilities.Result.ComplexTypes
@using BlogApp.Entities.Dtos
@model CategoryListDto
@{
    Layout = "_Layout";
    ViewBag.Title = "Kategoriler Anasayfa";
}
@if (Model.ResultStatus == ResultStatus.Success)
{
    @*Kategoriler listelenecek*@
    <div id="modalPlaceHolder" aria-hidden="true"></div>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">Kategoriler</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Kategoriler
        </div>
        <div class="card-body">
            <div class="spinner-border" role="status" style="display:none;">
                <span class="sr-only">Yükleniyor...</span>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered" id="categoriesTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Ad</th>
                            <th>Açıklama</th>
                            <th>Aktif mi?</th>
                            <th>Oluşturulma Tarihi</th>
                            <th>Oluşturan Kullanıcı</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var category in Model.Categories)
                        {
                                <tr name="@category.Id">
                                    <td>@category.Id</td>
                                    <td>@category.Name</td>
                                    <td>@category.Description</td>
                                    <td>@category.IsActive</td>
                                    <td>@category.CreatedDate.ToShortDateString()</td>
                                    <td>@category.CreatedByName</td>
                                    <td>
                                    <button class="btn btn-warning btn-sm btn-update" data-id="@category.Id"><span class="fas fa-edit text-white"></span></button>
                                        <button class="btn btn-danger btn-sm btn-delete" data-id="@category.Id"><span class="fas fa-minus-circle"></span></button>
                                    </td>
                                </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

@section Scripts{
    <script src="~/js/categoryIndex.js">
    </script>
}

BlogApp.Mvc/Areas/Admin/Views/Category/_CategoryAddPartial.cshtml
@using BlogApp.Entities.Dtos
@model CategoryAddDto

<div class="modal fade" role="dialog" aria-hidden="true" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><span class="fas fa-plus"></span> Kategori Ekle</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <form asp-area="Admin" asp-controller="Category" asp-action="Add" id="form-category-add" method="post">
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <div class="text-danger" asp-validation-summary="All" id="validation-summary" style="display:none"></div>@*Tüm hataları listelemek için*@
                    <div class="form-group">
                        <label asp-for="Name" class="form-check-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="form-check-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Note" class="form-check-label"></label>
                        <input asp-for="Note" class="form-control" />
                        <span class="text-danger" asp-validation-for="Note"></span>
                    </div>
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" asp-for="IsActive" />
                        <label asp-for="IsActive" class="form-check-label"></label>
                        <span class="text-danger" asp-validation-for="IsActive"></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-block" data-dismiss="modal"><span class="fas fa-times"></span> İptal</button>
                <button type="button" class="btn btn-primary btn-block" id="btnSave"><span class="fas fa-save"></span> Kaydet</button>
            </div>


        </div>
    </div>
</div>

BlogApp.Mvc/Areas/Admin/Views/Category/_CategoryUpdatePartial.cshtml
@using BlogApp.Entities.Dtos
@model CategoryUpdateDto

<div class="modal fade" role="dialog" aria-hidden="true" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><span class="fas fa-edit"></span> @Model.Name adlı kategori düzenleniyor...</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <form asp-area="Admin" asp-controller="Category" asp-action="Update" id="form-category-update" method="post">
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <input hidden="true" asp-for="Id" />
                    <div class="text-danger" asp-validation-summary="All" id="validation-summary" style="display:none"></div>@*Tüm hataları listelemek için*@
                    <div class="form-group">
                        <label asp-for="Name" class="form-check-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="form-check-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Note" class="form-check-label"></label>
                        <input asp-for="Note" class="form-control" />
                        <span class="text-danger" asp-validation-for="Note"></span>
                    </div>
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" asp-for="IsActive" />
                        <label asp-for="IsActive" class="form-check-label"></label>
                        <span class="text-danger" asp-validation-for="IsActive"></span>
                    </div>
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" asp-for="IsDeleted" />
                        <label asp-for="IsDeleted" class="form-check-label"></label>
                        <span class="text-danger" asp-validation-for="IsDeleted"></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-block" data-dismiss="modal"><span class="fas fa-times"></span> İptal</button>
                <button type="button" class="btn btn-warning btn-block" id="btnUpdate"><span class="fas fa-save"></span> Değişiklikleri Kaydet</button>
            </div>
        </div>
    </div>
</div>

BlogApp.Mvc/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Admin Home Page";
}

<div class="text-center">
    <h1 class="display-4">Burası Admin Area, hoş geldiniz.</h1>
    <p>Blog Area kısmına geçmek için <a asp-area="" asp-controller="Home" asp-action="Index">tıklayınız</a>.</p>
</div>

BlogApp.Mvc/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - Blog App</title>
    @await Html.PartialAsync("_LayoutCssPartial");
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Blog App</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Arama..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Ayarlar</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="login.html">Çıkış Yap</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        @await Html.PartialAsync("_LayoutSideBarNavPartial");
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Tüm hakları saklıdır &copy; Blog App 2022</div>
                        <div>
                            <a href="#">Gizlilik Politikası</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @await Html.PartialAsync("_LayoutJsPartial");
    @await RenderSectionAsync("Scripts", false);
</body>
</html>

BlogApp.Mvc/Areas/Admin/Views/Shared/_LayoutCssPartial.cshtml
<link href="/css/styles.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" rel="stylesheet" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
<link href="https://cdn.datatables.net/buttons/2.3.2/css/buttons.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" crossorigin="anonymous" />

BlogApp.Mvc/Areas/Admin/Views/Shared/_LayoutJsPartial.cshtml
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="/js/scripts.js"></script>
<script src="/js/site.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="/assets/demo/chart-area-demo.js"></script>
<script src="/assets/demo/chart-bar-demo.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="/assets/demo/datatables-demo.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/dataTables.buttons.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" crossorigin="anonymous"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

BlogApp.Mvc/Areas/Admin/Views/Shared/_LayoutSideBarNavPartial.cshtml
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Menü</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Kategoriler
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Article" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Makaleler
                </a>
                <a class="nav-link" href="index.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Yorumlar
                </a>
                <a class="nav-link" href="index.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Roller
                </a>
                <a class="nav-link" href="index.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Kullanıcılar
                </a>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Giriş Yapan Kullanıcı:</div>
            Administrator
        </div>
    </nav>
</div>

BlogApp.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Blog Home Page";
}

<div class="text-center">
    <h1 class="display-4">Burası Blog Area, hoş geldiniz.</h1>
    <p>Admin Area kısmına geçmek için <a asp-area="Admin" asp-controller="Home" asp-action="Index">tıklayınız</a>.</p>
</div>

BlogApp.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogApp.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogApp.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogApp.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BlogApp.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>